name: Validate JSON Schemas

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  validate-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install

      - name: Run schema validator
        run: npm run validate:schemas
